### ISSUE TITLE
路由守卫

### ISSUE THREAD

**Issue by xiaohuoni** [xiaohuoni/umi-antd-pro#1]
没有权限（退出登录之后），也可以直接访问所有页面

**Comment by xiaohuoni** [comment]
还未完成，需要UMI支持匹配添加路由守卫

**Comment by xiaohuoni** [comment]
https://github.com/umijs/umi/pull/403

**Comment by xiaohuoni** [comment]
umi还是没有约定式批量添加权限的方法，考虑写一个第三方插件先实现。

**Comment by luxueyan** [comment]
@xiaohuoni xiao  求分享

**Comment by xiaohuoni** [comment]
@luxueyan https://github.com/xiaohuoni/umi-plugin-authorize

**Comment by luxueyan** [comment]
@xiaohuoni   谢谢 先研究研究！
