### ISSUE TITLE
umi/locale无法使用npm安装，代码里面都是使用from ‘umi/locale’。这个怎么获取？

### ISSUE THREAD

**Issue by QDPeng** [xiaohuoni/umi-antd-pro#14]

**Comment by xiaohuoni** [comment]
这个其实是从umi里面获取的，其实应该安装umi-plugin-locale from umi-plugin-locale 
后面改成ts的，我都改了。

**Comment by xiaohuoni** [comment]
import { FormattedMessage, formatMessage } from 'umi-plugin-react/locale';
