### ISSUE TITLE
umi 数据流、路由 可能会想Hook方向发展。可能采用Hox，或者@reach/router有者方面的数据流改写计划么？

### ISSUE THREAD

**Issue by X-neuron** [xiaohuoni/umi-antd-pro#22]
如题。 dva  目前 来看 在Hook下完全可以被 hox 和 little-saga的use-saga替换..这方便有计划跟进么？
路由 考虑支持 @reach/router 么？来减少包大小么？

**Comment by xiaohuoni** [comment]
数据流切换请跟进使用 pro@5 https://github.com/ant-design/ant-design-pro/tree/v5
