### ISSUE TITLE
antd 计划升级到4.0以上么？

### ISSUE THREAD

**Issue by X-neuron** [xiaohuoni/umi-antd-pro#23]

**Comment by xiaohuoni** [comment]
这只是一个方案实践测试的项目，pro 官方已经升级到 antd@4 了。

**Comment by kkaaddff** [comment]
> 这只是一个方案实践测试的项目，pro 官方已经升级到 antd@4 了。

在别的帖子提到的tabs加keepalive版本的pro的仓库是哪个，可以给出一下么

**Comment by X-neuron** [comment]
> 在别的帖子提到的tabs加keepalive版本的pro的仓库是哪个，可以给出一下么

https://github.com/X-neuron/antdFront  没用keepalive。纯函数，纯原生，纯webpack，纯hook，支持微前端

**Comment by xiaohuoni** [comment]
@kkaaddff 就是这个仓库 。
