### ISSUE TITLE
项目启动报错

### ISSUE THREAD

**Issue by xu-Aurora** [xiaohuoni/umi-antd-pro#24]
<img width="1023" alt="截屏2020-06-03 下午5 01 29" src="https://user-images.githubusercontent.com/35291465/83617625-ed7bc380-a5bb-11ea-9f71-745fa89d08f1.png">

**Comment by Hill-V** [comment]
问题解决了没？

**Comment by xiaohuoni** [comment]
已解决 https://github.com/alitajs/umi-antd-pro/commit/c1d54b31ff26204fdcf11f77ea719df0ef1028a4
