### ISSUE TITLE
pro.alitajs.com 示例项目版本

### ISSUE THREAD

**Issue by kkaaddff** [xiaohuoni/umi-antd-pro#25]
这个https://pro.alitajs.com/ 
这个demo的代码并不是这个仓库，是那个仓库可以告知一下么

**Comment by xiaohuoni** [comment]
你好。就是这个仓库的。

**Comment by li9269391** [comment]
使用umi约定式路由多Tabs的Ant Design Pro（Antd Pro的实验项目）
你好，请问 pro.alitajs.com 这个实验项目还没开源出来吗？

**Comment by xiaohuoni** [comment]
就是现在这个仓库....
