### ISSUE TITLE
关于keep-alive的解决方案，请问带参数传递的路由如何处理？？

### ISSUE THREAD

**Issue by thelaurelyy** [xiaohuoni/umi-antd-pro#26]
在keep-alive的解决方案中，用了您提供的解决方法，但是当路由带参数传递，例如：'/system/user/:id'，请问如何进行匹配和处理呢？？

**Comment by xiaohuoni** [comment]
这个插件只是一个尝试，存在很多问题，我一直没抽出时间来处理，不建议在项目中使用。需要多 tabs 方案，可以使用 [umi-plugin-keep-alive](https://github.com/alitajs/umi-plugin-keep-alive) 插件实现，这里有一个[demo](https://codesandbox.io/s/umi-keep-alive-tabs-demo-knfxy)

**Comment by xiaohuoni** [comment]
有后续，在https://github.com/umijs/umi/issues/5748

**Comment by thelaurelyy** [comment]
首先感谢回复！~
不过我们在使用 ** umi-plugin-keep-alive**  的过程中发现，KeepAlive包裹的组件原本引用的antd样式全部丢失，是哪里使用不当吗？
