### ISSUE TITLE
能实现下点击菜单打开标签页吗，很多项目都需要，找了几个别人实现的，都差强人意。

### ISSUE THREAD

**Issue by chifangxiong** [xiaohuoni/umi-antd-pro#29]
能实现下点击菜单打开标签页吗，很多项目都需要，找了几个别人实现的，都差强人意。

**Comment by xiaohuoni** [comment]
这个项目已有这个功能

**Comment by chifangxiong** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
